language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
script:
  - mvn clean install
  - cd ./freemarker-generator-cli/target/appassembler/
  - sh ./run-examples.sh
  - cd ../../../freemarker-generator-maven-plugin-sample
  - mvn clean package